version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - '8000:8000'
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    environment:
      - VITE_API_BASE=http://localhost:8000
